name: Api Gateway Service CI

on:
  push:
    tags:
      - "apiGateway-v*.*.*"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  call-build:
    uses: ./.github/workflows/build-push-template.yaml
    with:
      service-name: apiGateway-service
      context: ./apiGateway-service
    secrets: inherit
