name: Auth Service CI

on:
  push:
    tags:
      - "auth-v*.*.*"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  call-build:
    uses: ./.github/workflows/build-push-template.yaml
    with:
      service-name: auth-service
      context: ./auth-service
    secrets: inherit
